Add VSCodium Docs
MichaIng/DietPi-Docs pull request #444
Opened 2021-04-20 23:45 UTC by ravenclaw900

Closes #443.
I couldn't think of anything to put in the tabs, so I'm open to suggestion.

2021-04-21 10:13 UTC, MichaIng commented
> I couldn't think of anything to put in the tabs, so I'm open to suggestion.

I haven't had a closer look, but from the official docs it seems that by default VSCodium uses a different extension marketplace, while it's possible to switch to the MS one: https://github.com/VSCodium/vscodium/blob/master/DOCS.md#extensions--marketplace
This would be a compromise solution instead of switching to MS VSCode, when user miss some extensions they know from VSCode.

Usually we have a logging tab, but I think for a desktop application that doesn't make much sense. But there would be a log file.

Also the update tab is trivial, but could be added:
````
VSCodium is installed via APT and can hence be updated by running the following commands from console:

```sh
apt update
apt install codium
```
````

2021-04-21 11:12 UTC, ravenclaw900 commented
> I haven't had a closer look, but from the official docs it seems that by default VSCodium uses a different extension marketplace, while it's possible to switch to the MS one

Later on in that section, it says that using the official repository might not be legal.  However, except for propriety MS extensions, all the extensions I use are in the Open VSX repository.

2021-04-23 08:01 UTC, StephanStS requested changes

2021-04-23 08:01 UTC, StephanStS commented on docs/software/programming.md
> +Documentation (Visual Studio Code): <https://code.visualstudio.com/docs>
Please add two spaces at the end of the line to have a correct newline between line 142 and 143.

2021-04-24 20:10 UTC, merged